import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MsmService {

  constructor() { }

  marka(){
    return [{ id: "Mercedes-Benz", Name: "Mercedes-Benz" }, { id: "DAF", Name: "DAF" }, { id: "BMC", Name: "BMC" }, { id: "Ford-Trucks", Name: "Ford-Trucks" }, { id: "Iveco", Name: "Iveco" }, { id: "MAN", Name: "MAN" }, { id: "Renault", Name: "Renault" }, { id: "Scania", Name: "Scania" }, { id: "Volvo", Name: "Volvo" }]
  }

  seri(){
    return [{ id: "Mercedes-Benz", Name: "Actros", sid: "Actros" }, { id: "Mercedes-Benz", Name: "Axor", sid: "Axor" }, { id: "Mercedes-Benz", Name: "Arocs", sid: "Arocs" }, { id: "DAF", Name: "105", sid: "105" }, { id: "DAF", Name: "ATI", sid: "ATI" }, { id: "DAF", Name: "CF", sid: "CF" }, { id: "DAF", Name: "XF", sid: "CF" }, { id: "BMC", Name: "Pro", sid: "Pro" }, { id: "BMC", Name: "Tuğra", sid: "Tuğra" }, { id: "Ford-Trucks", Name: "Cargo", sid: "Cargo" }, { id: "Ford-Trucks", Name: "F-Max", sid: "F-Max" }, { id: "Iveco", Name: "Eurostar", sid: "Eurostar" }, { id: "Iveco", Name: "Eurotech", sid: "Eurotech" }, { id: "Iveco", Name: "Starlis", sid: "Starlis" }, { id: "Iveco", Name: "S-Way", sid: "S-Way" }, { id: "MAN", Name: "26", sid: "26" }, { id: "MAN", Name: "F2000", sid: "F2000" }, { id: "MAN", Name: "TGA", sid: "TGA" }, { id: "MAN", Name: "TGS", sid: "TGS" }, { id: "MAN", Name: "TGX", sid: "TGX" }, { id: "Renault", Name: "Magnum", sid: "Magnum" }, { id: "Renault", Name: "Premium", sid: "Premium" }, { id: "Renault", Name: "T", sid: "T" }, { id: "Scania", Name: "G", sid: "G" }, { id: "Scania", Name: "L", sid: "L" }, { id: "Scania", Name: "R", sid: "R" }, { id: "Scania", Name: "S", sid: "S" }, { id: "Volvo", Name: "FH", sid: "FH" }, { id: "Volvo", Name: "FM", sid: "FM" }]
  }

  model(){
    return [{ sid: "Actros", Name: "1840" }, { sid: "Actros", Name: "1841" }, { sid: "Actros", Name: "1842" }, { sid: "Actros", Name: "1843" }, { sid: "Actros", Name: "1844" }, { sid: "Actros", Name: "1845" }, { sid: "Actros", Name: "1846" }, { sid: "Actros", Name: "1848" }, { sid: "Actros", Name: "1850" }, { sid: "Actros", Name: "1851" }, { sid: "Axor", Name: "1835 LS" }, { sid: "Axor", Name: "1840 LS" }, { sid: "CF", Name: "85.410" }, { sid: "CF", Name: "85.430" }, { sid: "CF", Name: "85.460 LD" }, { sid: "CF", Name: "95.480" }, { sid: "CF", Name: "105.460" }, { sid: "CF", Name: "105.480" }, { sid: "Pro", Name: "827" }, { sid: "Pro", Name: "1142" }, { sid: "Pro", Name: "1144" }, { sid: "Tuğra", Name: "TGR 1846" }, { sid: "Cargo", Name: "1838T" }, { sid: "Cargo", Name: "1842T" }, { sid: "Cargo", Name: "1846T" }, { sid: "F-Max", Name: "1850T" }, { sid: "Starlis", Name: "430" }, { sid: "Starlis", Name: "450" }, { sid: "Starlis", Name: "460 AS" }, { sid: "Starlis", Name: "460 AT" }, { sid: "Starlis", Name: "480" }, { sid: "S-Way", Name: "460" }, { sid: "S-Way", Name: "480" }, { sid: "S-Way", Name: "490" }, { sid: "S-Way", Name: "510" }, { sid: "S-Way", Name: "530" }, { sid: "S-Way", Name: "570" }, { sid: "F2000", Name: "19.422" }, { sid: "F2000", Name: "19.423" }, { sid: "F2000", Name: "19.463" }, { sid: "TGA", Name: "18.410" }, { sid: "TGA", Name: "18.430" }, { sid: "TGA", Name: "18.460" }, { sid: "TGA", Name: "18.480" }, { sid: "TGA", Name: "19.400" }, { sid: "TGS", Name: "18.400" }, { sid: "TGS", Name: "18.420" }, { sid: "TGS", Name: "18.440" }, { sid: "TGS", Name: "18.460" }, { sid: "TGX", Name: "18.400" }, { sid: "TGX", Name: "18.440" }, { sid: "TGX", Name: "18.470" }, { sid: "TGX", Name: "18.500" }, { sid: "TGX", Name: "18.510" }, { sid: "Magnum", Name: "480.19 T" }, { sid: "Premium", Name: "400.19T" }, { sid: "Premium", Name: "420.19" }, { sid: "Premium", Name: "420" }, { sid: "Premium", Name: "430.19T" }, { sid: "Premium", Name: "440.19" }, { sid: "Premium", Name: "450.18T" }, { sid: "Premium", Name: "460.18T" }, { sid: "Premium", Name: "460.19T" }, { sid: "T", Name: "460" }, { sid: "T", Name: "520" }, { sid: "G", Name: "124.420" }, { sid: "G", Name: "400" }, { sid: "G", Name: "420" }, { sid: "G", Name: "440" }, { sid: "R", Name: "400" }, { sid: "R", Name: "420" }, { sid: "R", Name: "440" }, { sid: "R", Name: "450" }, { sid: "R", Name: "500" }, { sid: "R", Name: "540" }, { sid: "S", Name: "500" }, { sid: "S", Name: "540" }, { sid: "FH", Name: "12.420" }, { sid: "FH", Name: "12.460" }, { sid: "FH", Name: "16.520" }, { sid: "FH", Name: "42 TB 440" }, { sid: "FH", Name: "42 TB 460" }, { sid: "FH", Name: "460" }, { sid: "FH", Name: "500" }, { sid: "FH", Name: "540" }, { sid: "FM", Name: "42 TB 450" }]
  }
}
